name:                srtree-eqsat
version:             0.2.0.0
github:              "githubuser/srtree-eqsat"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/srtree-eqsat#readme>

dependencies:
- base >= 4.7 && < 5
- srtree >= 1.0.0.4 && < 1.1
- bytestring >= 0.11 && < 0.12
- optparse-applicative >= 0.18 && < 0.19
- mtl >= 2.2 && < 2.3
- split
- hegg
- containers
- ieee754
- deriving-compat

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  srtree-eqsat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - srtree-eqsat
